server:
  port: ${PARTNER_TEST_SERVER_PORT:8082}

spring:
  data:
    redis:
      password: ${REDIS_TEST_PASSWORD:123456}
      cluster:
        nodes: ${REDIS_TEST_CLUSTER_NODES:127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005}

demo:
  datasource:
    crypto:
      secret: ${DATASOURCE_TEST_CRYPTO_SECRET:cloud-family-demo-test-datasource-crypto-secret}
    cloud:
      url: ${FA_CLOUD_TEST_DB_URL:jdbc:mysql://localhost:3306/fa-cloud-test?useSSL=false&allowPublicKeyRetrieval=true&preserveInstants=true&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true&characterEncoding=utf8}
      username: ${FA_CLOUD_TEST_DB_USERNAME:ENC(U0rj/0TFqN/ikdyYo1QcsZa9APbjTkdLYLth5ycDEk4=)}
      password: ${FA_CLOUD_TEST_DB_PASSWORD:ENC(O/mIkbzTm1uHasWUrJSMKaIDlfcpqXW6E8FFh3e0+Y0=)}
      maximum-pool-size: ${FA_CLOUD_TEST_DB_MAX_POOL_SIZE:5}
      minimum-idle: ${FA_CLOUD_TEST_DB_MIN_IDLE:1}
      connection-timeout: ${FA_CLOUD_TEST_DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${FA_CLOUD_TEST_DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${FA_CLOUD_TEST_DB_MAX_LIFETIME:1800000}
      validation-timeout: ${FA_CLOUD_TEST_DB_VALIDATION_TIMEOUT:5000}
      leak-detection-threshold: ${FA_CLOUD_TEST_DB_LEAK_DETECTION_THRESHOLD:0}
      pool-name: fa-cloud-test
    model:
      url: ${FA_MODEL_TEST_DB_URL:jdbc:mysql://localhost:3306/fa-model-test?useSSL=false&allowPublicKeyRetrieval=true&preserveInstants=true&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true&characterEncoding=utf8}
      username: ${FA_MODEL_TEST_DB_USERNAME:ENC(U0rj/0TFqN/ikdyYo1QcsZa9APbjTkdLYLth5ycDEk4=)}
      password: ${FA_MODEL_TEST_DB_PASSWORD:ENC(O/mIkbzTm1uHasWUrJSMKaIDlfcpqXW6E8FFh3e0+Y0=)}
      maximum-pool-size: ${FA_MODEL_TEST_DB_MAX_POOL_SIZE:5}
      minimum-idle: ${FA_MODEL_TEST_DB_MIN_IDLE:1}
      connection-timeout: ${FA_MODEL_TEST_DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${FA_MODEL_TEST_DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${FA_MODEL_TEST_DB_MAX_LIFETIME:1800000}
      validation-timeout: ${FA_MODEL_TEST_DB_VALIDATION_TIMEOUT:5000}
      leak-detection-threshold: ${FA_MODEL_TEST_DB_LEAK_DETECTION_THRESHOLD:0}
      pool-name: fa-model-test
