spring:
  application:
    name: xxl-job-admin
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  servlet:
    context-path: /xxl-job-admin

management:
  endpoints:
    web:
      exposure:
        include: health,info
