server:
  port: ${XXL_JOB_ADMIN_SERVER_PORT:8088}

demo:
  xxl-job-admin:
    access-token: ${XXL_JOB_ACCESS_TOKEN:default_token}
    executor-timeout-seconds: ${XXL_JOB_ADMIN_EXECUTOR_TIMEOUT_SECONDS:10}
